FROM sonarsource/sonar-scanner-cli:latest

WORKDIR /usr/src

COPY ./scripts/wait-it-out.sh sonar-project.properties ./
COPY app ./app

CMD bash ./wait-it-out.sh -t "server:9000/api/projects/search" -c "sonar-scanner"
