version: "3.3"

services:
  db:
    container_name: sonar_db
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar

  server:
    container_name: sonar_server
    image: sonarqube:latest
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_SEARCH_JAVAADDITIONALOPTS: -Dnode.store.allow_mmap=false
    ports:
      - 9000:9000

  scanner:
    container_name: sonar_scanner
    depends_on:
      - server
    build:
      context: .
      dockerfile: Dockerfile.scanner
    environment:
      SONAR_HOST_URL: "http://server:9000"
