version: "3.3"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./scripts:/usr/src

  server:
    image: sonarqube:latest
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - 9000:9000
    volumes:
      - data:/opt/sonarqube/data
      - logs:/opt/sonarqube/logs
      - extensions:/opt/sonarqube/extension

  scanner:
    image: sonarsource/sonar-scanner-cli:latest
    depends_on:
      - server
    environment:
      SONAR_HOST_URL: "http://server:9000"
    tty: true
    volumes:
      - ./:/usr/src
    command: bash ./wait-it-out.sh -t "server:9000" -c "sonar-scanner"


volumes:
  data:
  logs:
  extensions:
  postgresql:
  postgresql_data:
