version: 2.1
jobs:
  sonar:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true # allows us to cache the containers we use INSIDE our job container - they have to be downloaded in full each time otherwise
      - run:
          name: Make reports folder
          command: mkdir -p ~/reports
      - run:
          name: Ensure scripts executable
          command: chmod a+x wait-it-out.sh export-issues.sh get-status.sh
      - run:
          name: Start containers
          command: docker-compose -f docker-compose.yml up --build --abort-on-container-exit
      - run:
          name: Restart our DB container to dump issues
          command: docker start sonar_db
      - run:
          name: Create file with issues from DB container
          command: docker exec sonar_db bash /usr/src/export-issues.sh
      - run:
          name: Copy test artifacts
          command: docker cp sonar_db:/tmp/dump.json ~/reports/
      - run:
          name: Stop containers
          command: docker-compose -f docker-compose.yml down
      - store_artifacts:
          path: ~/reports

workflows:
  sast:
    jobs:
      - sonar
